### ISSUE TITLE
Menambahkan Tautan ke Demo Aplikasi

### ISSUE THREAD

**Issue by jefrydco** [jendrabayu/code-highlighter-dev#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Bayu. Mas juga sudah menambahkan Bulma sebagai kerangka kerja CSS nya. Hal lain yang menurut saya cukup menarik fitur unduh untuk setiap daftar kode yang disimpan. Keren Mas!

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

Semangat selalu ya! :muscle:

**Comment by jendrabayu** [comment]
Mas Raphael siapa mas?

**Comment by jefrydco** [comment]
Astaga Mas, mohon maaf Mas saya salah melihat di spreadsheet submisi nya. Mas Bayu datanya berdekatan sama Mas Raphael dan sepertinya saya melihat baris data yang salah. Sekali lagi mohon Maaf Mas. :pray: :sob:

**Comment by jendrabayu** [comment]
oalah santuy santuy mas, gimana apakah sudah bener yang tautan itu mas?

**Comment by jefrydco** [comment]
Siap Mas, mantap banget Mas tambahin di berkas readme.md. Bisa juga ditambahkan di bagian sidebar repositorinya yg saya contohin berikut.

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

Kalau sudah mungkin Mas bisa menutup isu ini. Terima kasih banyak Mas, jangan segan-segan untuk bertanya dan semangat selalu ya! 💪

**Comment by jendrabayu** [comment]
siap sudah mas
